/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tingeltangel.gui;

import java.awt.Color;
import java.awt.Component;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;
import tingeltangel.core.Tools;
import tingeltangel.core.Tupel;

/**
 *
 * @author martin
 */
public abstract class ChooseBook extends javax.swing.JDialog {

    /**
     * Creates new form ChooseBook
     */
    public ChooseBook(java.awt.Frame parent) {
        super(parent, false);
        initComponents();
        
        File[] books = Tools.getWorkingDirectory("books").listFiles();
        final LinkedList<Tupel<Integer, String>> list = new LinkedList<Tupel<Integer, String>>();
        for(int i = 0; i < books.length; i++) {
            if(books[i].isDirectory()) {
                DataInputStream in = null;
                try {
                    int id = Integer.parseInt(books[i].getName());
                    in = new DataInputStream(new FileInputStream(new File(books[i], "book.tbu")));
                    int _id;
                    // compatibility hack
                    int fileFormatVersion = in.readInt();
                    if(fileFormatVersion <= 15000) {
                        _id = fileFormatVersion;
                        fileFormatVersion = 0;
                    } else {
                        _id = in.readInt();
                        fileFormatVersion -= 15000;
                    }
                    if(id != _id) {
                        throw new IOException("dir-id=" + id + "; file-id=" + _id);
                    }
                    String name = in.readUTF();
                    String publisher = in.readUTF();
                    String author = in.readUTF();
                    in.close();
                    list.add(new Tupel(id, name + " (" + author + ")"));
                } catch(NumberFormatException nfe) {
                } catch(IOException ioe) {
                    ioe.printStackTrace(System.err);
                    try {
                        in.close();
                    } catch (IOException ex) {
                    }
                }
            }
        }
        
        bookList.setCellRenderer(new ListCellRenderer() {

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Tupel<Integer, String> book = (Tupel<Integer, String>)value;
                JLabel label = new JLabel(book.a + ": " + book.b);
                if(isSelected) {
                    label.setBackground(Color.black);
                } else {
                    label.setBackground(Color.white);
                }
                return(label);
            }
        });
        
        // add list to model
        
        bookList.setModel(new ListModel() {

            private HashSet<ListDataListener> dataListenerList = new HashSet<ListDataListener>();
            
            @Override
            public int getSize() {
                return(list.size());
            }

            @Override
            public Object getElementAt(int index) {
                return(list.get(index));
            }

            @Override
            public void addListDataListener(ListDataListener l) {
                dataListenerList.add(l);
            }

            @Override
            public void removeListDataListener(ListDataListener l) {
                dataListenerList.remove(l);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookList = new javax.swing.JList();
        button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bookList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(bookList);

        button.setText("OK");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 323, Short.MAX_VALUE)
                        .addComponent(button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public abstract void selected(File dir);
    
    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        
        Tupel<Integer, String> book = (Tupel<Integer, String>)bookList.getSelectedValue();
        if(book != null) {
            String id = Integer.toString(book.a);
            while(id.length() < 5) {
                id = "0" + id;
            }
            selected(new File(Tools.getWorkingDirectory("books"), id));
        }
        
    }//GEN-LAST:event_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChooseBook dialog = new ChooseBook(new javax.swing.JFrame()) {

                    @Override
                    public void selected(File dir) {
                        System.out.println(dir.getAbsolutePath());
                    }
                };
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList bookList;
    private javax.swing.JButton button;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
